target:
- charges
continuous_cols:
- age
- bmi
- children
categorical_cols:
- sex
- smoker
- region
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
dataloader_kwargs: {}
task: regression
head: LinearHead
head_config:
  layers: ''
embedding_dims:
- - 3
  - 2
- - 3
  - 2
- - 5
  - 3
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.001
loss: MSELoss
metrics:
- mean_squared_error
metrics_prob_input:
- false
metrics_params:
- {}
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.category_embedding
_model_name: CategoryEmbeddingModel
_backbone_name: CategoryEmbeddingBackbone
_config_name: CategoryEmbeddingModelConfig
layers: 64-32-16
activation: ReLU
use_batch_norm: false
initialization: kaiming
dropout: 0.0
batch_size: 32
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 100
min_epochs: 1
max_time: null
accelerator: auto
devices: -1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 3
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: false
track_grad_norm: -1
progress_bar: rich
precision: 32
trainer_kwargs: {}
optimizer: Adam
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
categorical_dim: 3
continuous_dim: 3
output_dim: 1
output_cardinality: null
categorical_cardinality:
- 3
- 3
- 5
embedded_cat_dim: 7
