target:
- Species
continuous_cols:
- SepalLength
- SepalWidth
- PetalLength
- PetalWidth
categorical_cols:
- Species
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: false
handle_unknown_categories: true
handle_missing_values: true
dataloader_kwargs: {}
task: classification
head: LinearHead
head_config:
  layers: ''
embedding_dims:
- - 4
  - 2
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.001
loss: CrossEntropyLoss
metrics:
- accuracy
metrics_prob_input:
- false
metrics_params:
- sub_params_list:
  - task: multiclass
    num_classes: 3
    top_k: 1
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.category_embedding
_model_name: CategoryEmbeddingModel
_backbone_name: CategoryEmbeddingBackbone
_config_name: CategoryEmbeddingModelConfig
layers: 4-15-3
activation: ReLU
use_batch_norm: false
initialization: kaiming
dropout: 0.1
batch_size: 10
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 70
min_epochs: 1
max_time: null
accelerator: cpu
devices: -1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 3
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: false
track_grad_norm: -1
progress_bar: rich
precision: 32
trainer_kwargs: {}
optimizer: SGD
optimizer_params:
  weight_decay: 1.0e-05
  momentum: 0
  dampening: 0
  nesterov: false
  maximize: false
  foreach: null
  differentiable: false
  fused: null
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
categorical_dim: 1
continuous_dim: 4
output_dim: 3
output_cardinality:
- 3
categorical_cardinality:
- 4
embedded_cat_dim: 2
